name: Build Geode Mod

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - id: android32
            os: ubuntu-latest
            target: Android32

          - id: android64
            os: ubuntu-latest
            target: Android64

    name: Build ${{ matrix.config.target }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      # Bước này sẽ tự động build và TỰ ĐỘNG upload file mod (.geode) lên Artifacts.
      # Không cần bất kỳ lệnh upload hay combine thủ công nào khác.
      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: false
          target: ${{ matrix.config.target }}
