name: Build Geode Mod

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build Mod (Android 32 & 64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Gọi duy nhất 1 Action để tự động tự build cả 2 nền tảng Android và tự động gộp lại thành file .geode hoàn chỉnh
      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: Android32 Android64
          combine: true

      # Xuất file mod Show Position thành phẩm ra tab Artifacts
      - name: Upload Final Mod
        uses: actions/upload-artifact@v4
        with:
          name: Show-Position-Mod
          path: ${{ steps.build.outputs.output-path || steps.build.outputs.build-output-path || '**/*.geode' }}
